name = "absensi-sd-ypu"
compatibility_date = "2026-05-28"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "absenpjok"
database_id = "c1a5a342-13dd-40f9-958f-3315f89112d4"

